### ISSUE TITLE
The "already subscribed" check should be in the subscription form instead of the purchase widget.

### ISSUE THREAD

**Issue by Jaesin** [apigee/apigee-m10n-drupal#103]
https://github.com/apigee/apigee-m10n-drupal/pull/39 adds an "Already Subscribed" notice and hides the subscribe form when using the `apigee_subscribe_form` field formatter when rendering a rate plan. This logic should be moved to the "purchase" form so the rate plan subscribe page ( `/user/{user}/monetization/package/{package}/plan/{rate_plan}/subscribe`) can also benefit from this improvement.

**Comment by shadcn** [comment]
@Jaesin Should the submit button be disabled if already subscribed or do we hide the whole form?

**Comment by Jaesin** [comment]
The purchase page should look like the purchase form if a rate plan is configured to render `purchase` as a form.
