### ISSUE TITLE
[Regression] Status page redirected to edge error page.

### ISSUE THREAD

**Issue by Jaesin** [apigee/apigee-m10n-drupal#104]
The `/admin/reports/status` page is redirected to the "Cannot reach management server" page if the connection credentials are not configured on the site. The status page should reachable so more information will be available to anyone trying to debug connection issues.

**Comment by cnovak** [comment]
Related to #111

**Comment by shadcn** [comment]
Yeah this is same issue as #111. Fixed in https://github.com/apigee/apigee-m10n-drupal/pull/124.

**Comment by shadcn** [comment]
Fixed. https://github.com/apigee/apigee-m10n-drupal/pull/124
