### ISSUE TITLE
"Configuration" admin menu broken after install

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-m10n-drupal#111]
## Description
If you install the Apigee Edge module and the M10n module (and no Admin Toolbar module), you cannot configure Edge once installing the modules.

## Steps to reproduce
1. Install D8 using drupal composer: `composer create-project drupal-composer/drupal-project:8.x-dev d8-devportal --stability dev --no-interaction`
2. After site is installed, install Apigee Edge and Apigee Monetization ( issues do not happen when you select only Apigee edge)
3. Click on "Configuration", in order to navigate to configure Edge connection settings.

__Expected:__ You will see a listing of sub menu items that are under the “Configuration” menu item
__Actual:__ The “cannot reach management server” error is shown, with no way to reach the Edge connection settings page to fix the issue.

<img width="1331" alt="Screen Shot 2019-06-03 at 1 41 12 PM" src="https://user-images.githubusercontent.com/613093/58829734-ca63b000-8605-11e9-923d-b630d83c7fc2.png">

**Comment by shadcn** [comment]
Fixed: https://github.com/apigee/apigee-m10n-drupal/pull/124
