### ISSUE TITLE
Group the "Purchased plans" into 2 tables: Active and Future Plans, Canceled and Expired Plans

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-m10n-drupal#114]
Relevant comp:

https://projects.invisionapp.com/d/main/default/#/console/16939246/359615113/preview

**Comment by cnovak** [comment]
Can be worked on after #105

**Comment by shadcn** [comment]
PR sent for review: https://github.com/apigee/apigee-m10n-drupal/pull/121

**Comment by jacine** [comment]
In addition to what's in #121 already, this issue should also match the comps with regard to the table structure, labels, and contents.

**Comment by shadcn** [comment]
PR merged: https://github.com/apigee/apigee-m10n-drupal/pull/121
