### ISSUE TITLE
Docs: To add the "add money" button to prepaid balance page

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-m10n-drupal#115]
To add the "add money" button to prepaid balance page:

Configuration > Apigee Edge > Monetization > Prepaid Balance
add credit tab

Need to add product for each currency, one product can only work with one currency, or at least a variant for each

**Comment by jbennett13** [comment]
Published here:  https://www.drupal.org/docs/8/modules/apigee-monetization/enable-the-apigee-monetization-add-credit-module#step-4-add-an-add-credit-button
