### ISSUE TITLE
Consolidate the local tasks on Team pages, as we did for User pages in #105.

### ISSUE THREAD

**Issue by jacine** [apigee/apigee-m10n-drupal#120]
The tabs currently look like this:
<img width="1073" alt="Screen Shot 2019-06-06 at 12 29 50 PM" src="https://user-images.githubusercontent.com/60979/59049802-cf6b6e00-8856-11e9-9b67-2bba24fb6bb4.png">

- View
- Edit
- Delete
- Prepaid balance
- Members
- Team Apps
- Purchased plans
- Billing Details

This should be changed to: 

- Details (formerly View)
- Edit
- Delete
- Team Apps (make this the default tab)
- Members (note there is a [separate issue](https://github.com/apigee/apigee-edge-drupal/issues/216) to change this to "Team Members")
- Balance and plans
  - Prepaid balance
  - Purchased plans
  - Billing Details

**Comment by shadcn** [comment]
I created PR https://github.com/apigee/apigee-m10n-drupal/pull/130 to move the monetization tabs under "Balance and plans". 

As for the other changes, they need to happen in Apigee Edge and there's ongoing discussion here: https://github.com/apigee/apigee-edge-drupal/issues/219
