### ISSUE TITLE
Change user facing strings of "Subscription/s" to "Purchase Plan/s"

### ISSUE THREAD

**Issue by jacine** [apigee/apigee-m10n-drupal#125]
As part of this task the following things should be changed:

1. The subscription entity's annotation labels should be changed to "Purchased plan/s".

2. The table headers on `/user/1/monetization/subscriptions` don't use the entity label):
  - From "Active and Future Subscriptions" to "Active and Future Plans"
  - From "Cancelled and Expired Subscriptions" to  "Canceled and Expired Plans"

3. Change the empty messages on `/user/1/monetization/subscriptions` to be a single generic and not using the entity label, e.g. "There are no results to display".

**Comment by cnovak** [comment]
I thought the main reason of entity labels is so that the labels can be used instead of hardcoded strings. Wouldn't it make more sense to use the label in the table headers and empty messages now that we have a consistent named label?

**Comment by jacine** [comment]
> I thought the main reason of entity labels is so that the labels can be used instead of hardcoded strings. Wouldn't it make more sense to use the label in the table headers and empty messages now that we have a consistent named label?

Are you referring to bullet 2?  If so, at some point I had a bullet in my list to change the rate plan entity annotation from "Rate plan/s" to "Plan/s" as well, but I removed it while we were chatting, b/c I thought we said hard-coding these table headers was ok.  Did we still want to make that change, and use the label for these headers?

I also don't know that we do have 100% consistently named labels... We don't have both present and past tense. As I was writing this up, it occurred to me that "Active and Future Purchase Plans" is wrong, and we would want "Active and Future Purchas*ed* Plans".

**Comment by Jaesin** [comment]
With #128, this is what we get with the entity label used in the table headers.

<img width="951" alt="image" src="https://user-images.githubusercontent.com/159693/59517291-191c1000-8e78-11e9-8365-afb5e0281268.png">

With the changes to using purchased plans as an entity label, we can probably remove many of the setting around which label should be used on the configuration page.
