### ISSUE TITLE
Change Subscription entity to PurchasedPlans 

### ISSUE THREAD

**Issue by jacine** [apigee/apigee-m10n-drupal#126]
Change `Subscription` entity to `PurchasedPlan`.  The labels should be already changed to "purchased plan" and "purchased plans" via #125, but this ticket is to rename the actual entity to make it match our decision to call this a purchased plan instead of a subscription. 

As discussed yesterday, this would be good to do before 1.0. 

This relates to #125, but is substantially more work, which is why it's in a separate issue.

## Background
The Edge API there is a `plan` entity, but after you purchase a `plan` you can make calls to the `v1/mint/organizations/:org_name/developers/:developer_id/developer-accepted-rateplans` to get a list of entities which we are naming `PurchasedPlans`.

**Comment by cnovak** [comment]
Changing all occurrences of "Subscription/s" to "Purchase plan/s" in code should happen automatically if we are using labels.  Is this task to make sure labels are being used?

**Comment by cnovak** [comment]
Updated description
