### ISSUE TITLE
Docs: Include a step asking users to increase max_allowed_packet on Mariadb before enabling  "Apigee Monetization Add Credit".   Else users are very likely to run in to database errors

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-m10n-drupal#127]
PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /home/D8/web/core/lib/Drupal/Core/Database/Statement.php:59                                                                                                       

Steps that need to be followed documented at: https://support.plesk.com/hc/en-us/articles/213414749-How-to-set-the-value-of-max-allowed-packet-or-wait-timeout-for-MySQL-on-a-Plesk-server-

**Comment by kscheirer** [comment]
Hmm, this problem used to come up often with Views module and its super-large cache writes. The D7 docs explicitly mention max_allowed_packet at https://www.drupal.org/docs/7/system-requirements/database-server, which is still relevant here.

Unfortunately the D8 docs at https://www.drupal.org/docs/8/system-requirements/database-server and https://www.drupal.org/node/259580 are not quite as clear on the topic, though the in the comments you can see max_allowed_packet is specifically mentioned.

**Comment by jbennett13** [comment]
@arunz6161  Arun, is this an additional step we need to add in the section about enabling Add Credit, because it is a consistent issue with most installs?  Or could we start a Troubleshooting section for Monetization? If it is a less frequently encountered error, I'd rather keep the install/enable instructions for Add Credit and Drupal Commerce more streamlined.  Thanks for your thoughts.

**Comment by arunz6161** [comment]
@jbennett13 I like the idea of starting a troubleshooting section. This issue might not be seen frequently. Let me know if this helps

**Comment by jbennett13** [comment]
Published here:  https://www.drupal.org/docs/8/modules/apigee-monetization/troubleshoot-issues
