### ISSUE TITLE
Docs: Unable to configure the checkout page to just show unit price instead of quantity and product variation when m10n is installed along with kickstart.

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-m10n-drupal#129]

**Comment by arunz6161** [comment]
Refer attach screenshots
Expected- (without kickstart)
![Screen Shot 2019-06-12 at 11 25 54 AM](https://user-images.githubusercontent.com/4381612/59483877-3cb56b00-8e24-11e9-95ce-14c1e265d10d.png)

With kickstart

<img width="1390" alt="Screen Shot 2019-06-13 at 9 44 23 PM" src="https://user-images.githubusercontent.com/4381612/59483916-771f0800-8e24-11e9-97f6-85b6c82f44f8.png">

**Comment by shadcn** [comment]
@arunz6161 Can you try the following?

1. From the admin toolbar, go to Commerce --> Configuration --> Orders --> Order item types.
2. Under operations select Manage form display. (Depending on your setup your order item type might be named Default).
3. Click on Add to cart in the secondary tabs.
4. Drag and drop the unit price.
5. Select Unit price under Widget and save.

![m10n-219](https://user-images.githubusercontent.com/124599/59526670-85375c00-8eea-11e9-9418-5396eb5034fe.gif)

(I see this ticket is under m10n. Should this be under kickstart? We are working on having kickstart ship with all these configured btw).

**Comment by arunz6161** [comment]
Thanks @arshad that works. For some reason, i was overlooking the "Add to cart" tab in the settings page.

**Comment by arunz6161** [comment]
We could clarify this in docs to prevent other users from running in to the issue.

**Comment by jbennett13** [comment]
I've added the instructions here (in M10n docs) which will be incorporated by reference in the Kickstart docs, once M10n is integrated there:  https://www.drupal.org/docs/8/modules/apigee-monetization/enable-the-apigee-monetization-add-credit-module#step-3-add-products-to-the-store
