### ISSUE TITLE
WSOD on subscribing to a rate plan

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-m10n-drupal#140]
**Describe the bug**
WSOD on subscribing to specific rate plans

**To Reproduce**
1. Go to http://dev-mint-d8.devportal.apigee.io
2. Create a new account.
3. Login in as the new user and try purchasing plan "fooo-lsla_future_plan_sixty"
4. WSOD

**Expected behavior**
no WSOD. Ideally plan purchase should complete or user should be asked to add a payment method.

**Additional context**
Watchdog logs:

TypeError: Argument 2 passed to Drupal\Core\Link::fromTextAndUrl() must be an instance of Drupal\Core\Url, null given, called in /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/modules/contrib/apigee_m10n/modules/apigee_m10n_add_credit/src/AddCreditService.php on line 404 in Drupal\Core\Link::fromTextAndUrl() (line 74 of /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/lib/Drupal/Core/Link.php) #0 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/modules/contrib/apigee_m10n/modules/apigee_m10n_add_credit/src/AddCreditService.php(404): Drupal\Core\Link::fromTextAndUrl('Add credit', NULL) #1 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/modules/contrib/apigee_m10n/modules/apigee_m10n_add_credit/apigee_m10n_add_credit.module(116): Drupal\apigee_m10n_add_credit\AddCreditService->insufficientBalanceErrorMessageAlter(Object(Drupal\Core\StringTranslation\TranslatableMarkup), Object(Drupal\apigee_m10n\Entity\Subscription)) #2 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/lib/Drupal/Core/Extension/ModuleHandler.php(539): apigee_m10n_add_credit_apigee_m10n_insufficient_balance_error_message_alter(Object(Drupal\Core\StringTranslation\TranslatableMarkup), Object(Drupal\apigee_m10n\Entity\Subscription), NULL) #3 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/modules/contrib/apigee_m10n/src/Entity/Form/SubscriptionForm.php(236): Drupal\Core\Extension\ModuleHandler->alter('apigee_m10n_ins...', Object(Drupal\Core\StringTranslation\TranslatableMarkup), Object(Drupal\apigee_m10n\Entity\Subscription)) #4 [internal function]: Drupal\apigee_m10n\Entity\Form\SubscriptionForm->save(Array, Object(Drupal\Core\Form\FormState)) #5 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/lib/Drupal/Core/Form/FormSubmitter.php(111): call_user_func_array(Array, Array) #6 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/lib/Drupal/Core/Form/FormSubmitter.php(51): Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object(Drupal\Core\Form\FormState)) #7 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/lib/Drupal/Core/Form/FormBuilder.php(590): Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object(Drupal\Core\Form\FormState)) #8 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/lib/Drupal/Core/Form/FormBuilder.php(319): Drupal\Core\Form\FormBuilder->processForm('subscription_fo...', Array, Object(Drupal\Core\Form\FormState)) #9 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/lib/Drupal/Core/Entity/EntityFormBuilder.php(61): Drupal\Core\Form\FormBuilder->buildForm('subscription_fo...', Object(Drupal\Core\Form\FormState)) #10 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/modules/contrib/apigee_m10n/src/Entity/Controller/RatePlanSubscribeController.php(93): Drupal\Core\Entity\EntityFormBuilder->getForm(Object(Drupal\apigee_m10n\Entity\Subscription), 'default', Array) #11 [internal function]: Drupal\apigee_m10n\Entity\Controller\RatePlanSubscribeController->subscribeForm(Object(Drupal\user\Entity\User), Object(Drupal\apigee_m10n\Entity\RatePlan)) #12 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #13 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #14 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #15 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #16 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #17 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #18 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #19 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #25 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #26 /srv/bindings/f753de56e91142fa94af8a04b54e1936/code/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #27 {main}.

**Version Info**
This can be the version you can see on admin/modules in Drupal or 
the output of this command: `composer show`.  Add Drupal core and
other version information if needed.

**Comment by shadcn** [comment]
Running the latest apigee_m10n and I can confirm this bug. Fix incoming.
