### ISSUE TITLE
Add Credit Price range fields throw Exception

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-m10n-drupal#148]
**Describe the bug**
When configuring the "Add Credit" "Price Range", if you put an invalid number into the "Minimum" or "Maximum" fields, you will get an exception thrown/WSOD.

**To Reproduce**
1. Follow the [Add credit documentation](https://www.drupal.org/docs/8/modules/apigee-monetization/enable-the-apigee-monetization-add-credit-module) documentation.
2. When filling in the "Price Range" fields, put in `34,00` for the minimum or maximum fields

**Expected behavior**
Error message should be displayed to user that the value is not a number.

**Actual behavior**
Get an exception thrown: `CommerceGuys\Intl\Exception\InvalidArgumentException</em>: The provided value &quot;203,00&quot; is not a valid number or numeric string.`

**Screenshots**
<img width="571" alt="invalid-price-range" src="https://user-images.githubusercontent.com/613093/60352571-f3fdc600-997c-11e9-901d-538ef3449b43.png">

**Additional context**

**Version Info**
 1.0.0-rc1

**Comment by shadcn** [comment]
@cnovak I can confirm this bug. I'm working on a fix. But it seems to be a bug in commerce module. Try disabling the range field and use the default price field. I'm seeing the same exception.
