### ISSUE TITLE
"Add credit" button on prepaid balance page does not display

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-m10n-drupal#150]
**Describe the bug**
The add credit button does not show up on the balance page until after you have added money to your account, but you cannot add money w/out having the button (catch-22 situation).

**To Reproduce**
1. Follow [Step 4: Add an “Add Credit” button to your prepaid balance page](https://www.drupal.org/docs/8/modules/apigee-monetization/enable-the-apigee-monetization-add-credit-module#step-4-add-an-add-credit-button)

**Expected behavior**
Button is displayed

**Actual behavior**
Button is not displayed. However, if you already have a prepaid balance, button will be displayed.

**Screenshots**
<img width="1005" alt="no-button" src="https://user-images.githubusercontent.com/613093/60368344-7ef2b680-99a5-11e9-867a-ce47a44f58e5.png">

**Version Info**
RC-1

**Comment by jacine** [comment]
I think this was fixed by #155.  Feel free to reopen if that's wrong.
