### ISSUE TITLE
Developer/Developer categories are not displayed

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-m10n-drupal#151]
**Describe the bug**
Plans can be created that are only displayed for a developer or developer category.  This module is not displaying those plans.

**To Reproduce**
1. In Edge, create a plan with the audience "Developer category" or "Developer"
2. Log in as that developer or a developer/company in that developer category
3. Look for the plan you created, notice it is not displayed

**Expected behavior**
The plan should be displayed

**Additional context**
The calls being made to the Edge API are:
`https://api.enterprise.apigee.com/v1/mint/organizations/{org}/monetization-packages/{package/productbundle}/rate-plans`, but this will not show developer or developer category plans.

The call needs to be `https://api.enterprise.apigee.com/v1/mint/organizations/{org}/monetization-packages/{package/productbundle}/developers/{email}/rate-plans`

Also note that to put a developer in a developer category, you need to make an API call. Do a **GET** call to https://api.enterprise.apigee.com/v1/organizations/:org_name/developers/:email, then do a **PUT** to the same resource adding the **MINT_DEVELOPER_CATEGORY** custom attribute.  The [docs about this say](https://docs.apigee.com/api-platform/monetization/manage-developer-categories#api) to to a **PUT** to https://api.enterprise.apigee.com/v1/**mint**/organizations/{org_name}, but you need to make a **PUT** to the non-mint resource.

**Version Info**
all

**Comment by shadcn** [comment]
@cnovak it looks like the SDK has something to handle this `\Apigee\Edge\Api\Monetization\Controller\RatePlanControllerInterface::getEntities`. I'll look into this.

See `standard` param: `Flag that specifies whether to display all types of rate plans, including standard, developer, and developer category. Set to true to display standard rate plan types only. Set to false to display all types.`

https://apidocs.apigee.com/monetize/apis/get/organizations/%7Borg_name%7D/monetization-packages/%7Bpackage_id%7D/rate-plans

**Comment by shadcn** [comment]
@cnovak I'm closing this in favor of #162. @Jaesin has added more details in the ticket. Feel free to re-open.

**Comment by shadcn** [comment]
Reopening this since #162 is for team membership and subscriptions and the original issue here is for developer view access. I'll continue working on PR #159
