### ISSUE TITLE
Subscribing to rate plans with overlapping product results in error

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-m10n-drupal#168]
**Describe the bug**
Subscribing to rate plans with overlapping product results in "The website encountered an unexpected error. Please try again later."

**To Reproduce**
1. With portal pointing to "tsnow-mint", purchase rate plan "arunz"
2. Try purchasing rate plan "arunzfee"
3. Ideally you should the error message complaining about overlapping products
4. You end up getting - "The website encountered an unexpected error. Please try again later."
5. NOTE: you do see the expected error message when you click back on browser.

**Expected behavior**
error message complaining about overlapping products
**Screenshots**

![Screen Shot 2019-07-11 at 3 12 15 PM](https://user-images.githubusercontent.com/4381612/61089157-1d900600-a3ef-11e9-91e9-d73f0f3a81a5.png)

**Additional context**

**Version Info**
m10n version : 8.x-1.0-rc1
edge version: 8.x-1.0

**Comment by arlina-espinoza** [comment]
Hi @arunz6161 ,

I followed the steps and did get an appropriate error message as shown below. I tested with edge version 8.x-1.0, and current dev version of m10n (what will be released today as rc2). Could you try testing once rc2 is released?
![Screenshot_2019-07-12 Purchase arunzfee Apigee Developer Portal Kickstart M10N](https://user-images.githubusercontent.com/4062676/61149021-c26d1a80-a4a5-11e9-96d2-bc36d6bdf760.png)

**Comment by arunz6161** [comment]
@arlina-espinoza - I am unable to reproduce this issue on  rc2. Closing this out.
