### ISSUE TITLE
Mark the Apigee Monetization Add Credit module as experimental.

### ISSUE THREAD

**Issue by Jaesin** [apigee/apigee-m10n-drupal#169]
As we close in on 1.0 for the Apigee monetization module, we should evaluate the features and implementation of the Add Credit sub-module. If usability seems OK for this module, we can close this. If it is determined that there are some implementation details that we may want to improve, we should mark the add credit sub-module as experimental until the improvements can be implemented. Some improvements could break backwards compatibility such as changes in how add credit products are configured.

Some things we may want to review:

- [Administrative usability] Admin `/admin/config/apigee-edge/monetization/add-credit`.
- [Administrative usability] Configuring add credit products.
- [Usability] The way the add credit product is displayed could use some review for possible improvements.
- [Implementation] When the purchased credit is added to the account it would be nice if we can report back to the order that the balance was successfully added or at least have an admin view of balance adjustments. The `BalanceAdjustmentJob` might need to be abandoned but that's probably OK since the job can't be retried anyway.

**Describe the solution you'd like**
Change the module package to "package: Apigee (Experimental)".
Do a through review of the add credit sub module.

**Comment by arlina-espinoza** [comment]
Let's scope this down to mark the module as experimental; created new issue to thoroughly review the add credit module (#178).

**Comment by shadcn** [comment]
Fixed via #180
