### ISSUE TITLE
Admins can subscribe to a developer rate plan that was not created for them.

### ISSUE THREAD

**Issue by Jaesin** [apigee/apigee-m10n-drupal#175]
When viewing rate plans as a developer (i.e. /user/1/plans) the developer should not be able to purchase a rate plan unless they are the assigned developer or have the developer category.

**To Reproduce**

1. Create a developer rate plan assigned to a developer. 
2. View the rate plan as an admin that is not the assigned developer.
3. Observe you are able to purchase the rate plan.

**Expected behavior**

An admin would not be able to purchase a rate plan that is assigned to a different developer. It might be best if the plan developer context was required to view the rate plan to avoid confusion. If an admin can view the rate plan with the assigned developers context (via `/user/{assigned_developer_uid}/plans`), that should be enough.

Relates to #151.

**Comment by arunz6161** [comment]
Removing this from 8.x-1.0 milestone- we can document this as a known issue and pick this up a later point.
