### ISSUE TITLE
Add requirement module for easier setup after install

### ISSUE THREAD

**Issue by arlina-espinoza** [apigee/apigee-m10n-drupal#190]
Follow up of #178:
`The main pain points of administrative usability have to do with all of the required configuration that needs to be done before actually configuring and using this module (set up a store, configure currencies supported in Edge, creating the products). The Kickstart install profile does a nice job of setting things up transparently, and it would be nice to move/replicate that behavior through a module setup form - see apigee/apigee-devportal-kickstart-drupal#196 (comment).`

**Comment by arlina-espinoza** [comment]
This is related to the work being done in https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/241 - Will be porting some of that here.

**Comment by arlina-espinoza** [comment]
To do:

- Update drupal.org repo and give access to all related.
- Add the drupal/requirement module to this module.

**Comment by shadcn** [comment]
To do:

- [x] Update drupal.org repo and give access to all related.
- [x] Add the drupal/requirement module to this module.
