### ISSUE TITLE
Monetized products visible to non-subscribed developers

### ISSUE THREAD

**Issue by casba** [apigee/apigee-m10n-drupal#193]
**Describe the bug**
Monetized products should not be visible for a user if they are not subscribed to the relevant rate plan. After having created new products, bundling the products into an API Product Bundle, and assigning that bundle to a rate plan the products in question are still visible to a developer that has not subscribed to the rate plan. 

Other products that are part of bundle/rate plan are not visible as expected. All products are of public visibility.

**To Reproduce**
1. Create one or more API products that are publicly visible and auto-approved.
2. (Optional) Go to the create app page in drupal and verify they are available to select.
3. Create a new API Product Bundle and add all created products from 1.
4. Create a new Rate Plan with the API Product Bundle from 3.
5. Clear the cache in Drupal, and attempt to create a new App. The apps from 1 should not be visible, but in my case they are.

**Expected behavior**
A developer should not be able to see a product that is part of an API Product Bundle/Rate Plan unless they are subscribed to the rate plan.

**Additional context**
The drupal user in question (developer) has admin permissions.

**Version Info**
apigee/apigee-client-php              2.0.3
apigee/apigee_devportal_kickstart     1.4.0
drupal/core                           8.7.5

**Comment by giteshk** [comment]
@casba did you mean to close this issue?

**Comment by casba** [comment]
Hey gitesh, I did. It was simply a misconfiguration with a post dated start
date for the rate plan.
