### ISSUE TITLE
Update M10N module to check if org is hybrid

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-m10n-drupal#203]
Update M10N module to check if org is hybrid - At the moment, hybrid does not support monetization.

**Comment by arlina-espinoza** [comment]
The property `features.isMonetizationEnabled` is not set for Hybrid orgs, so the module should already be checking for that. Although looking into[ the code](https://github.com/apigee/apigee-m10n-drupal/blob/270d4def161da8c57e7aa410ccfc7d4b3bd84137/apigee_m10n.install#L34-L66), it seems to be checking this property during `runtime`, and not during `install`, so maybe we could move also add the check for this property to the install phase. What do you think @arshad ?

**Comment by cnovak** [comment]
It looks like that runtime check is only for checking for the condition " If monetization is disabled after module has been installed", but this would not happen. If an org is monetized or not, you need to create a new org to remove/add monetization.

**Comment by arunz6161** [comment]
closing this one and replacing this with a new one where the plan is to implement:

1. Check if org is monetized during installation
2. Check if org is monetized when configuring org setting on config page.
