### ISSUE TITLE
404 when selecting Details of rate plan

### ISSUE THREAD

**Issue by mikesson** [apigee/apigee-m10n-drupal#204]
**Describe the bug**
When catalog view mode is set to Teaser (Configuration --> Apigee monetization --> Rate Plans --> Rate plan settings --> Catalog view mode) and `Purchase` format is set to `Rendered Form` (Configuration --> Apigee monetization --> Rate Plans --> Manage display --> Purchase), selecting rate plan details results in 404 page. 

**To Reproduce**
1. Spin up drupal instance through https://github.com/apigee/docker-apigee-drupal-kickstart
2. Enable all remaining Apigee and Apigee monetization modules 
3. Select "Pricing & Plans" from the top nav, then select "View Details" of a rate plan
4. See 404 error

**Expected behavior**
Rate plan details show up.

**Additional context**
Solved it by changing "Rendered Form" to "Link to form" in "manage display" settings.
.
I've tested other combinations, too, which failed:
"Default"  & "Rendered Form" --> 404 at "/plans" page
"Default" & "Link to Form" --> Inconsistent UI in HTML page

**Comment by flogei** [comment]
Purchasing a Plan also throws the error in the /purchase page

**Comment by shadcn** [comment]
@mikesson Thanks for the detailed write-up. I'm trying to reproduce this issue. What's the path that is showing 404?

**Comment by cnovak** [comment]
@flogei will close this ticket, but put on another comment w/answer to @arshad 's question if you still need help on this, thx
