### ISSUE TITLE
500 Service unavailable after Purchasing Rate Plan

### ISSUE THREAD

**Issue by flogei** [apigee/apigee-m10n-drupal#205]
**Describe the bug**
When purchasing a rate plan I land on the /purchase page with an error message "The website encountered an unexpected error. Please try again later."

**To Reproduce**
1. Configure Monetization and manual Payment provider according to https://www.drupal.org/docs/8/modules/apigee-monetization/manage-payment-gateways
2. Go to 'Pricing & plans'
3. Choose a Rate plan (does not matter which type) and click 'purchase'

**Expected behavior**
Purchase the rate plan so I can do API calls and get charged for it accordingly.

**Additional context**
Drupal Log message: 

Location | http://localhost:8080/user/10/monetization/product-bundle/basic-ix9e/plan/basic-ix9e_free/purchase
-- | --
Referrer | http://localhost:8080/user/10/monetization/product-bundle/basic-ix9e/plan/basic-ix9e_free
Message | InvalidArgumentException: The URI 'some_url' is invalid. You must use a valid URI scheme. in Drupal\Core\Url::fromUri() (line 281 of /var/www/portal/web/core/lib/Drupal/Core/Url.php).
Severity | Error

**Version Info**
apigee_edge: 8.x-1.1
apigee_m10n: 8.x-1.1

**Comment by arunz6161** [comment]
@flogei Please confirm if you have configured the private file system as recommended at :  https://www.drupal.org/docs/8/modules/apigee-edge/configure-the-connection-to-apigee-edge#configure-private-file

**Comment by arunz6161** [comment]
@flogei are you still blocked ?

**Comment by arlina-espinoza** [comment]
@arunz6161 I haven't been able to replicate this issue. 
@flogei Could you give us more info? It looks like the error is on some URL validation, on what entity are you using `some_url`?

**Comment by flogei** [comment]
As a background on the config I have: I am using the drupal container https://github.com/apigee/docker-apigee-drupal-kickstart

You were right, this was missing the private file system setting. I fixed that but still have the same error.

What do you mean by on what entity I am using `some_url` ? Where else to look for for more info that I can provide you with?

**Comment by kscheirer** [comment]
Its from the error message in the initial post: `InvalidArgumentException: The URI 'some_url' is invalid. You must use a valid URI scheme.` Doesn't say _where_ some_url is coming from, but it must be somewhere.

**Comment by arlina-espinoza** [comment]
@flogei @arunz6161 I'm testing using the [drupal container](https://github.com/apigee/docker-apigee-drupal-kickstart) and a monetized org, and can't reproduce the error yet. 
@flogei Could you enable the `apigee_debug` module, add `{response_formatted}` to the debug output, then trigger the error again and send us both the apigee request log and the full error log as it appears in watchdog. It would help us figure out which request is failing for you, and on what file it is erro-ing out.

**Comment by flogei** [comment]
thx for the input for getting more output.

Searching for the "some_url" I see this entry as the culprit but I don't know what the entry is I am looking at though.

![image](https://user-images.githubusercontent.com/49034668/70322989-edc51d00-182b-11ea-8182-b66bbdff3ae9.png)

does this help? Otherwise I dont see anything useful in the debug or dont know a way to export more from the debug logs in a shareable log.

**Comment by arlina-espinoza** [comment]
Thanks for the info @flogei . It looks like the module is trying to format an invalid URL on the terms and conditions link, so that is something that we should follow up on.
The quickest fix, meanwhile, would be to write a valid (full) URL for your terms and conditions, as described in this page: https://docs.apigee.com/api-platform/monetization/specify-terms-and-conditions.
Let us know if that helps.

**Comment by flogei** [comment]
That did the trick, thx for your help!!

**Steps to resolve:** Enter a valid URL in the Terms and Conditions in the Organization Profile

**Comment by arunz6161** [comment]
Created a follow up to validate URLs: https://github.com/apigee/apigee-m10n-drupal/issues/220
