### ISSUE TITLE
How we are handling terms and conditions while creating team in Drupal 8?

### ISSUE THREAD

**Issue by robin0888** [apigee/apigee-m10n-drupal#206]
As terms and conditions handled at org end with some custom code in D7 while creating a company/team.
How's this scenario we're handling in D8 at the code level?

Thanks

**Comment by cnovak** [comment]
I moved this under the m10n project, and will close this issue since it looks like @arlina-espinoza gave a good explanation.  Add another comment if we did not answer this completely and we will reopen it, thanks
