### ISSUE TITLE
How to associate a rate plan or purchase plan in Drupal 8 pro-grammatically?

### ISSUE THREAD

**Issue by robin0888** [apigee/apigee-m10n-drupal#208]
The below code we used to handle the rate plan associated with the company in Drupal 7
```
$config = devconnect_default_org_config();

$rateplanobj = new RatePlan($packid,$config);

$rateplanobj->setRatePlans($company_id,$planid);
```

**I'm looking for the same for D8?**

**Comment by cnovak** [comment]
Check out how the [teamPurchaseForm() method in TeamPurchaseRatePlanController](https://github.com/apigee/apigee-m10n-drupal/blob/8.x-1.x/modules/apigee_m10n_teams/src/Entity/Controller/TeamPurchaseRatePlanController.php#L49) creates a plan for a company, you can do the same thing.

Drupal.org has [documentation on using the Entity API](https://www.drupal.org/docs/8/api/entity-api/working-with-the-entity-api), check out those examples also.

We are also working on a developer guide sections of our modules to help out with getting started, check out the start of our [Monetization Developer Guide](https://www.drupal.org/docs/8/modules/apigee-monetization/apigee-monetization-developer-guide).

Here is some code to get you started:
```
  $rate_plan = $this->entityTypeManager->getStorage('rate_plan')->load('my_rate_plan_id');
  $team = $this->entityTypeManager->getStorage('team')->load('my_team_id');

  // Create a purchased_plan entity starting immediately
  $purchased_plan  = $this->entityTypeManager->getStorage('purchased_plan')->create([
      'ratePlan' => $rate_plan,
      'company' => new Company(['id' => $team->id()]),
      'startDate' => new \DateTimeImmutable(),
    ]);

    // Save the plan.
    $purchased_plan->save();
```

**Comment by robin0888** [comment]
thanks @cnovak
