### ISSUE TITLE
Billing Type not displayed for newly registered users

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-m10n-drupal#212]
**Describe the bug**
The billing type is not displayed for newly registered users in system, displayed in red:

<img width="886" alt="billing-type missing" src="https://user-images.githubusercontent.com/613093/72194624-3c358080-33c3-11ea-9f14-c9b056c932d7.png">

**To Reproduce**
1. Register on a developer portal that is connected to a monetized org
2. Click on **My account**
3. Click on **Balance and plans**
4. Click on **Billing details**
4. View that `Billing Type` is not set to any value.

**Expected behavior**
A developer should be set to "PREPAID" or "POSTPAID" when created

**Screenshots**

**Version Info**
`drupal/apigee_m10n                       1.2.0        Apigee Edge Monetization for Drupal`

**Comment by cnovak** [comment]
It looks like this is due to the Edge API not showing the custom attribute for the developer. For a new developer, the data response to `/v1/organizations/{{org}}/developers/testjan10@test.com` is:

```
{
  "apps": [],
  "companies": [],
  "email": "testjan10@test.com",
  "developerId": "7e38d3f9-77a0-4e46-b627-6a1e5d29f04d",
  "firstName": "test",
  "lastName": "test",
...
  "status": "active",
  "attributes": [
    {
      "name": "MINT_DEVELOPER_LEGAL_NAME",
      "value": "TEST_USER_01"
    }
  ],
  "createdAt": 1578700820521,
  "createdBy": "admin@test.com",
  "lastModifiedAt": 1578700950566,
...
}
```

The attribute `MINT_BILLING_TYPE` is missing. Will follow up w/Monetization API team (b/147515954)

**Comment by cnovak** [comment]
**Workaround:** Change the billing type in the Apigee.com user interface to "PREPAID" to allow the developer to see the prepaid balance tab in their profile.

**Comment by cnovak** [comment]
## Fix
API Team is working on this issue, but there is also a fix we can do on our side. Instead of using the Edge API `/v1/organizations/{{org}}/` we should use `/v1/mint/organizations/{{org}}/` to get user data:

```
curl --request GET 'https://api.enterprise.apigee.com/v1/mint/organizations/{{org}}/developers/testjan10@test.com' \
--header 'Content-Type: application/json'
```

From API team:
>  the best practice for accessing mint data is to use the mint APIs instead of edge APIs. We do not guarantee that mint-specific data will be available when calling edge APIs. In addition, Mint APIs more cleanly handle this data, eg they're not attributes on the developer but an actual field.

**Comment by shadcn** [comment]
@cnovak What's the status from the API team?

**Comment by cnovak** [comment]
@arshad , the comment above named *Fix* should have all info on what we need to do. Let me know if you need any more details.

**Comment by shadcn** [comment]
@cnovak Yeah. Just wanted to make sure before we switch API. I'll do this now and run tests.

**Comment by arlina-espinoza** [comment]
Clarifying the scope of this ticket: we should only switch to using the monetized endpoint (`v1/mint`) for developers that are used in m10n-related functionality. All other calls to the API remain the same.
