### ISSUE TITLE
Re-test Add Credit in monetization project. Found an issue when setting up a demo that it doesn't work with the latest commerce module.

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-m10n-drupal#215]

**Comment by arlina-espinoza** [comment]
Using Kickstar distribution with monetization enabled, followed instructions on [how to enable the add credit module](https://www.drupal.org/docs/8/modules/apigee-monetization/enable-the-apigee-monetization-add-credit-module).

The expectation after following the above is that after using the "add credit" button in a user's "prepaid balance" page, and checking out (using a manual payment gateway), the new balance would be reflected. 

That was not happening: the checkout and order completed correctly, but the balance was not updated, and "refreshing" the balance did not help. No errors were logged on watchdog either.

Some more info we need @giteshk :
 - Was monetization enabled during the installation of the site of after? (We might need to follow up with an issue on Kickstart).
- Provide version of Drupal core and relevant modules (apigee_edge, apigee_m10n and commerce, please).

**Comment by giteshk** [comment]
Yes monetization was enabled during the install process 

Drupal Version . 8.8.1
Commerce Version: 8.x-2.14
Apigee Edge Version: 8.x-1.4
Monetization Version: 8.x-1.2
