### ISSUE TITLE
Recurring Payments

### ISSUE THREAD

**Issue by mikesson** [apigee/apigee-m10n-drupal#218]
**Is your feature request related to a problem? Please describe.**
Recurring payments are often required when looking at prepaid developer scenarios. As prepaid developers can run out of credit, a recurring payment setup helps to avoid visiting the portal every month (or other period) to top up credits. Even though postpaid developers are an option, prepaid with recurring payments provides a higher level of self-service (and avoids integration with 3rd party billing engines if payment gateways can be used instead).

**Describe the solution you'd like**
A recurring payment option for prepaid developers. This can be either outside (in payment gateway) or inside the Apigee module, depending on the simplest maintenance path.

**Additional context**
What was the workflow of the D7 Worldpay recurring module and how does it relate to the current payment gateway entities in Commerce for D8?

**Comment by shadcn** [comment]
@mikesson I've been looking into recurring/subscriptions for adding credit today and here's what I have so far. 

I tried a few solutions (contrib modules and custom code) and it looks like [Commerce Recurring](https://www.drupal.org/project/commerce_recurring) is our best bet. Here's how you can test it:

### Step 1: Install modules
- Enable the Commerce Recurring and the Commerce Payment Example module.

For subscriptions to work, we need an on-site payment gateway. We are going to use Payment Example to test.

### Step 2: Configure payment gateway

- Go to Commerce —> Configuration —> Payment —> Payment gateways.
- Add a new payment gateway. Use Example (On-site). This is required to recurring payment to work.

### Step 3: Configure billing schedule
- Go to Commerce —> Configuration —> Payment —> Billing Schedules.
- Add a billing schedule. Example monthly.

### Step 4: Update product variant
- Go to Commerce —> Configuration —> Products —> Product variation types.
- Edit the add credit variation type and check “Allow subscriptions”. Save.

### Step 5: Update products
- Edit the add credit products' variations and set the billing schedule for each one.


### How does it work?

When a user adds credit to balance, a subscription (temporary orders) will be created. 

You can view all subscriptions by visiting Commerce —> Subscriptions.

For recurring subscriptions to work, make sure Cron is properly configured.

⚠️Here be dragons: Commerce Recurring is still in beta so expect some bugs (feel free to report them here and we can figure it out together)

**Comment by cnovak** [comment]
Closing, #240 will take care of docs
