### ISSUE TITLE
Use the mint team/company API endpoint to fetch team attributes instead of the management API

### ISSUE THREAD

**Issue by arlina-espinoza** [apigee/apigee-m10n-drupal#224]
Follow up for https://github.com/apigee/apigee-m10n-drupal/pull/221#issuecomment-589496019. The only thing that bothers me is that I don't see the company endpoint documented in the official API, although the endpoint does exists, and we already have a controller for it in the apigee-client-php library (https://github.com/apigee/apigee-client-php/blob/2.x/src/Api/Monetization/Controller/CompanyController.php):
 ```
https://api.enterprise.apigee.com/v1/mint/organizations/{{org_name}}/companies/{{company}}
```

@cnovak / @jbennett13 Is documentation for this endpoint missing, or is this endpoint something that we cannot rely on or being deprecated? (See https://apidocs.apigee.com/api-reference/content/monetization-apis)

**Comment by arunz6161** [comment]
Log this against Apigee documentation.

**Comment by cnovak** [comment]
I put in feedback to Apigee docs team about this: b/157566883

**Comment by cnovak** [comment]
Response from API team:
> It makes sense to GET the Mint entity to access Mint-specific properties if you just wish to display or act on the info, since they have been parsed, validated, and transformed if necessary. POST, PUT, and DELETE methods are not supported.

Due to this, I am going to close this issue since the concept was to replace all calls with the Monetization API resource which is not possible.
