### ISSUE TITLE
Update/create steps needed to configure m10n Add credit

### ISSUE THREAD

**Issue by arlina-espinoza** [apigee/apigee-m10n-drupal#226]
After changes done in https://github.com/apigee/apigee-m10n-drupal/pull/223 and https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/323, we need to update the documentation to match.

1. Kickstart docs: Update instructions for setting up monetization during installer
2. Kickstart docs: Update/create how to install monetization after installing if not done during installer
3. M10n docs: Update/create Steps needed to configure m10n

**Comment by cnovak** [comment]
@arshad can you lay out any details needed for @jbennett13 to update, or update docs yourself?

**Comment by shadcn** [comment]
> 1. Kickstart docs: Update instructions for setting up monetization during installer

Do we have docs for setting up monetization in Kickstart? I couldn't find it.

> 2. Kickstart docs: Update/create how to install monetization after installing if not done during installer

If you do not enable monetization during instllation, then the steps are similar to `apigee_m10n`. [These docs](https://www.drupal.org/docs/8/modules/apigee-monetization/enable-the-apigee-monetization-add-credit-module) still applies. See also the notes below.

> 3. M10n docs: Update/create Steps needed to configure m10n

So I looked at the docs for enabling monetization, the only thing that changed is that now that `requirement.module` is in `apigee_m10n`, we could add a note to the [Add Credit documentation](https://www.drupal.org/docs/8/modules/apigee-monetization/enable-the-apigee-monetization-add-credit-module) to let users know they can follow suggestions from the requirement reports to quickly setup add credit.

Something along the lines of: "Apigee Monetization module ships with suggestions (helpers?) to quickly setup Add credit. See the requirements report at **Reports** --> **Requirements Report**."

**Comment by jbennett13** [comment]
Updated here:  https://www.drupal.org/docs/8/modules/apigee-monetization/enable-the-apigee-monetization-add-credit-module
