### ISSUE TITLE
Option to automatically create a test payment gateway

### ISSUE THREAD

**Issue by arlina-espinoza** [apigee/apigee-m10n-drupal#227]
The Add credit submodule has a requirements page that facilitates the configuration of the module. For the payment gateway, it only checks if one is installed or sends you to a page to add a new one. An idea for improvement would be to ask if the user would like to set a default manual test payment gateway, and if so, do it automatically (like the Kickstart installer).

**Comment by shadcn** [comment]
Created a PR here https://github.com/apigee/apigee-m10n-drupal/pull/233
