### ISSUE TITLE
Provide usage details for both prepaid and postpaid developers

### ISSUE THREAD

**Issue by kurtkanaskie** [apigee/apigee-m10n-drupal#228]
Neither prepaid or postpaid developers can see their current usage. 
Prepaid can see summary usage via "Prepaid balance" tab.
In Edge Monetization Reports, a Revenue type report will show both prepaid and postpaid usages, with or without developer filtering.

These reports can be created using Edge API with or without DevCriteria using for both prepaid and postpaid developers:
https://apidocs.apigee.com/monetize/apis/post/organizations/%7Borg_name%7D/%7Breport_type%7D
Or for a specific developer, via URL path segment:
https://apidocs.apigee.com/monetize/apis/post/organizations/%7Borg_name%7D/developers/%7Bdeveloper_id%7D/revenue-reports

The output is a CSV file.

This would be a great feature enhancement that many customers have asked for.

For example:
```
curl -n -X POST \
  https://api.enterprise.apigee.com/v1/mint/organizations/amer-demo13/revenue-reports \
  -H 'Content-Type: application/json' \
  -d '{
	"fromDate": "2020-03-01 00:00:00",
	"toDate": "2020-04-01 00:00:00",
	"showTxDetail": true,
	"showSummary": true,
	"devCriteria": [{
		"id": "18a91b9c-05bc-4801-a919-6e8945918b13",
		"orgId": "amer-demo13"
	}],
	"transactionTypes": [
		"PURCHASE",
        	"CHARGE",
        	"REFUND",
        	"CREDIT",
        	"SETUPFEES",
        	"TERMINATIONFEES",
        	"RECURRINGFEES"
	],
	"currencyOption": "LOCAL",
	"groupBy": [
		"PACKAGE",
		"PRODUCT",
		"DEVELOPER",
        	"APPLICATION",
        	"RATEPLAN"
	]
}'
```

Another example for same thing but different API
```
curl -n -X POST \
  https://api.enterprise.apigee.com/v1/mint/organizations/amer-demo13/developers/18a91b9c-05bc-4801-a919-6e8945918b13/revenue-reports \
  -H 'Content-Type: application/json' \
  -d '{
	"fromDate": "2020-03-01 00:00:00",
	"toDate": "2020-04-01 00:00:00",
	"showTxDetail": true,
	"showSummary": true,
	"transactionTypes": [
		"PURCHASE",
        	"CHARGE",
        	"REFUND",
        	"CREDIT",
        	"SETUPFEES",
        	"TERMINATIONFEES",
        	"RECURRINGFEES"
	],
	"currencyOption": "LOCAL",
	"groupBy": [
		"PACKAGE",
		"PRODUCT",
		"DEVELOPER",
        	"APPLICATION",
        	"RATEPLAN"
	]
}'
```

**Comment by shadcn** [comment]
@kurtkanaskie Just wanted to let give you a quick update. We are currently working on this. Thank you.

**Comment by kurtkanaskie** [comment]
Thanks, I've discussed with @giteshk a bit a few days ago.
If you need anything, please reach out.
