### ISSUE TITLE
Prepaid Balance - "Previous Balance" ?

### ISSUE THREAD

**Issue by mikesson** [apigee/apigee-m10n-drupal#234]
Hi, I'm wondering where the "Previous Balance" field is retrieved from in the Management API as I wasn't able to find the field there. Also, I have topped up balance twice in a row and still see 0 in "Previous Balance". Could be a bug, but for now just keen to see how and when this field populates.

**Comment by shadcn** [comment]
@mikesson The previous balance is retrieved from the following GET request:

`GET /v1/mint/organizations/{org}/developers/{developer}/prepaid-developer-balance?billingMonth={MONTH}&billingYear={YYYY}`

```json
{
  "developerBalance" : [ {
    "approxTaxRate" : 0,
    "currentBalance" : 172.0000,
    "currentTotalBalance" : 172.0000,
    "currentUsage" : 0,
    "id" : "id",
    "month" : "APRIL",
    "previousBalance" : 172.0000, <----
    "supportedCurrency" : {},
    "tax" : 0.0000,
    "topups" : 22.0000,
    "usage" : 0.0000,
    "year" : 2020
  }
  ....
```

> Also, I have topped up balance twice in a row and still see 0 in "Previous Balance". 

Did you try refreshing the balances? Or a cache rebuilt?

**Comment by shadcn** [comment]
@mikesson did you figure it out? I'm going to mark this ticket as done. Feel free to re-open it if you have any other questions. Thank you.
