### ISSUE TITLE
Plans page not update after purchase a plan , Still developer can purchase the same plan..

### ISSUE THREAD

**Issue by SajithAthukorala** [apigee/apigee-m10n-drupal#235]
**Describe the bug**
Plans page not update after purchase a plan , Still developer can purchase the same plan. and sometimes get the error saying ,**""The website encountered an unexpected error. Please try again later""**
error log 
`Error: Call to a member function extractFormValues() on null in Drupal\apigee_edge\Entity\Form\FieldableEdgeEntityForm->copyFormValuesToEntity() (line 85 of /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/modules/contrib/apigee_edge/src/Entity/Form/FieldableEdgeEntityForm.php)

#0 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/Entity/EntityForm.php(336): Drupal\apigee_edge\Entity\Form\FieldableEdgeEntityForm->copyFormValuesToEntity(Object(Drupal\apigee_m10n\Entity\PurchasedPlan), Array, Object(Drupal\Core\Form\FormState))
#1 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/modules/contrib/apigee_edge/src/Entity/Form/FieldableEdgeEntityForm.php(71): Drupal\Core\Entity\EntityForm->buildEntity(Array, Object(Drupal\Core\Form\FormState))
#2 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/modules/contrib/apigee_m10n/src/Entity/Form/FieldableMonetizationEntityForm.php(43): Drupal\apigee_edge\Entity\Form\FieldableEdgeEntityForm->buildEntity(Array, Object(Drupal\Core\Form\FormState))
#3 [internal function]: Drupal\apigee_m10n\Entity\Form\FieldableMonetizationEntityForm->validateForm(Array, Object(Drupal\Core\Form\FormState))
#4 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/Form/FormValidator.php(82): call_user_func_array(Array, Array)
#5 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/Form/FormValidator.php(275): Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object(Drupal\Core\Form\FormState))
#6 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/Form/FormValidator.php(118): Drupal\Core\Form\FormValidator->doValidateForm(Array, Object(Drupal\Core\Form\FormState), 'purchased_plan_...')
#7 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/Form/FormBuilder.php(577): Drupal\Core\Form\FormValidator->validateForm('purchased_plan_...', Array, Object(Drupal\Core\Form\FormState))
#8 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/Form/FormBuilder.php(320): Drupal\Core\Form\FormBuilder->processForm('purchased_plan_...', Array, Object(Drupal\Core\Form\FormState))
#9 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/Entity/EntityFormBuilder.php(61): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\apigee_m10n\Entity\Form\PurchasedPlanForm), Object(Drupal\Core\Form\FormState))
#10 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/modules/contrib/apigee_m10n/src/Entity/Controller/PurchaseRatePlanController.php(86): Drupal\Core\Entity\EntityFormBuilder->getForm(Object(Drupal\apigee_m10n\Entity\PurchasedPlan), 'default', Array)
#11 [internal function]: Drupal\apigee_m10n\Entity\Controller\PurchaseRatePlanController->purchaseForm(Object(Drupal\user\Entity\User), Object(Drupal\apigee_m10n\Entity\RatePlan))
#12 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#13 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#14 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#15 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#16 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#17 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#18 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#20 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#21 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#22 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#23 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#24 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#25 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#26 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#27 {main}`

`Error: Call to undefined method Drupal\apigee_m10n\Entity\RatePlan::hasTranslation() in Drupal\quickedit\QuickEditController->metadata() (line 150 of /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/modules/quickedit/src/QuickEditController.php)

#0 [internal function]: Drupal\quickedit\QuickEditController->metadata(Object(Symfony\Component\HttpFoundation\Request))
#1 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#2 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#3 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#4 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#5 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#6 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#7 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /srv/bindings/958ac5b73a084a65b003bac8afe2f255/code/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#16 {main}`

**To Reproduce**
1. Go to /user/61/plans  and puchase a plan
2. after purchase you can see still that plan is available for the user .
3. now click again the same plan and see the above error results . 

**Additional context**
Is this related to cache configuration?

**Version Info**
drupal/apigee_api_catalog                1.2.0        Apigee API Catalog for Drupal
drupal/apigee_edge                       1.8.0        Apigee Edge for Drupal.
drupal/apigee_m10n                       1.4.0        Apigee Edge Monetization for Drupal

apigee/apigee-client-php                 2.0.4        Client library for connecting to the Apigee Edge API.
apigee/apigee_devportal_kickstart        1.12.0       A fast demo and starting point for Apigee Developer Portals.

**Comment by shadcn** [comment]
@SajithAthukorala You're right this is cache related. I've been able to reproduce this bug and pushed a PR for this here: https://github.com/apigee/apigee-m10n-drupal/pull/239

We'll review, merge it and create a new release.

Thank you
