### ISSUE TITLE
Deprecate FieldableMonetizationEntityForm

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-m10n-drupal#236]
Properly deprecate FieldableMonetizationEntityForm and use FieldableEdgeEntityForm instead.

Follow up for https://github.com/apigee/apigee-edge-drupal/pull/400

**Comment by arunz6161** [comment]
Clean up task to be taken up during 2.x release

**Comment by mxr576** [comment]
But marking it deprecated and removing its usages can already happen.

**Comment by cnovak** [comment]
True @mxr576 , let's review this as a task before 2.0 @arunz6161
