### ISSUE TITLE
Document Recurring Payments

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-m10n-drupal#240]
In #218 , the question was asked how to do recurring payments. Let's take that advice from @arshad and add it to a doc page with a caveat at top that the module is in beta and that they can report back w/feedback if they see any issues.

**Comment by arunz6161** [comment]
@zakiya could you please test the steps to enable recurring payment with m10n module before we document it?

**Comment by zakiya** [comment]
@arunz6161 Sure thing.

**Comment by zakiya** [comment]
@arshad's instructions in #218 work as described. Additional notes:

- Assumes Apigee Kickstart with credentials an monetization enabled on install.
- Required fields not specified can be filled in with any information.

**Comment by cnovak** [comment]
@jbennett13 this would be good to document as a higher priority

**Comment by jbennett13** [comment]
Added to documentation in M10n module docs, and referenced from Kickstart with M10n docs.  https://www.drupal.org/docs/contributed-modules/apigee-monetization/enable-recurring-payments

Closing as complete.
