### ISSUE TITLE
Issues with Monetization module T&Cs section 

### ISSUE THREAD

**Issue by cgcoyle** [apigee/apigee-m10n-drupal#257]
On our Drupal Portal we are using monetization module :https://www.drupal.org/project/apigee_m10n
We are facing issue were:

1:  the Terms and Condition checkbox and links are visible for some admin users and for others it is not visible.
2: the Purchase Plan Button is not visiable for non-admin users .
3: We need to have access to the "Quota" set for the product so that we can show user how many hits they will get for the plan they are viewing .

Regards
Ciaran Coyle
Lead Developer , NDC Exchange
E-Mail: ciaran.coyle@sita.aero
Direct: +353 74 91 94740
Mobile: +353 86 8093378
CVS: 293 4740Address: SITA \| Building One \| Letterkenny Office Park \| Letterkenny, Co. Donegal \| Ireland

See attached screen shots 

## Actual Behavior
When testing teasers we observe that some users get the T&C check box others dont 

The Purchase plan button is not showing to normal non-admin user 

WE ahve no way to show the Quota set for a plan 

## Expected Behavior
We want T& C to always show
We want purchase plan to show 
We need access to the Plan Qouta

## Screenshots

![image](https://user-images.githubusercontent.com/77631882/104938870-963e2e00-59a7-11eb-81f8-417733791e34.png)

## Notes
We will set up demo to describe the issue in depth if required 

## Version Info
Drupal 8 
MOnetization module : /apigee_m10n

**Comment by raakesh-blokhra** [comment]
@cgcoyle We are looking into this issue. We will get back to you if more information is needed. Thanks.

**Comment by cgcoyle** [comment]
Thanks @raakesh-blokhra 
@phdhiren can you give some detail on possible resolution time frame ? 
Due to this issue We are currently blocked from releasing monetization features which is impacting our ability to onboard customers and create revenue .  Please advise asap.

**Comment by cnovak** [comment]
I am not sure if we can tell the resolution time frame until we can reproduce the issue. This is also multiple issues in one ticket, so we may need to break it apart into separate issues. 

Did you start with our [Apigee Kickstart](https://www.drupal.org/project/apigee_devportal_kickstart) distribution, or did you add the modules to an existing site?

- Can you [check permissions](https://www.drupal.org/docs/contributed-modules/apigee-monetization/configure-access-permissions) to make sure the proper roles can purchase plans?
- The fields available on a rate plan can be configured as an admin at:  Configuration  > Apigee Monetization > Rate Plans. The fields available are only the fields on the actual rate plan entity coming from the Apigee API. If you need other fields, you may want to create a custom page that lists the rate plans, then link them to the purchase page.  Check out our [rate plan configuration documentation](https://www.drupal.org/docs/8/modules/apigee-monetization/configure-rate-plan-settings).
- The [terms and conditions only shows up for persons who have not accepted the latest terms and conditions](https://github.com/apigee/apigee-m10n-drupal/blob/ada9bf5b2f4ca7b5e6534d130f92f034b00ccb5a/src/Plugin/Field/FieldWidget/TermsAndConditionsWidget.php#L132), which is stored in Apigee. Could it be the developer already accepted the terms and conditions? You can verify through the Apigee API or through the [Apigee Edge Interface](https://www.apigee.com).

**Comment by cgcoyle** [comment]
Thanks Chris

@Shubham Arora<mailto:Shubham.Arora@sita.aero> can you please comment and inform Chris about the history of our introduciton  of the Monetization module .
Also I believe we have tested and verified the permissions .
It is very unsatifactory that the Plan Quota is not exposed , introduing a custom call to apigee to get this data may be required .

WE did think that perhaps a previous T&C acceptance may have been reason but testing seems to prove contrary .


Regards

Ciaran Coyle
Lead Developer , NDC Exchange

[/Users/helenporter/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_2038408485]
[cid:image005.png@01D3A748.A75BC6D0]

E-Mail:   ciaran.coyle@sita.aero<mailto:ciaran.coyle@sita.aero>
Direct:   +353 74 91 94740
Mobile: +353 86 8093378
CVS:   293 4740
Address:  SITA | Building One | Letterkenny Office Park | Letterkenny, Co. Donegal | Ireland


**Upcoming Leave :NONE*

Join the conversation:
[cid:image003.jpg@01D43478.620101A0]<http://www.sita.aero/resources/sita-social>
www.sita.aero<http://www.sita.aero/>
Please consider your environmental responsibility before printing

**Comment by cgcoyle** [comment]
Hi Chris,

Thanks for the details and the documentation. It helped me to understand the functionality behind T&Cs and rate plan purchase.


  *   I have verified Terms and Conditions using Apigee APIs and found that after Accepting T&C the checkbox is removed from the rate plan detail page.
  *   Rate plan purchase button is now visible for all users after changing the permission.

I may need to do some customization to display quota of all products at rate plan display page.


Regards,
Shubham Arora
____________________________________________________
SITA | 4th Floor | Tower B | ASF Towers |
Udyog Vihar - Ph-IV | Gurugram – 122001 | Haryana | INDIA
Mob: +918287273407

From: Ciaran Coyle <Ciaran.Coyle@sita.aero>
Sent: 27 January 2021 14:44
To: apigee/apigee-m10n-drupal <reply@reply.github.com>; API COE <API.CoE@SITA.AERO>; Shubham Arora <Shubham.Arora@sita.aero>
Subject: RE: [EXT] Re: [apigee/apigee-m10n-drupal] Issues with Monetization module T&Cs section (#257)

Thanks Chris

@Shubham Arora<mailto:Shubham.Arora@sita.aero> can you please comment and inform Chris about the history of our introduciton  of the Monetization module .
Also I believe we have tested and verified the permissions .
It is very unsatifactory that the Plan Quota is not exposed , introduing a custom call to apigee to get this data may be required .

WE did think that perhaps a previous T&C acceptance may have been reason but testing seems to prove contrary .


Regards

Ciaran Coyle
Lead Developer , NDC Exchange

[/Users/helenporter/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_2038408485]
[cid:image002.png@01D6F4E4.13A37A90]

E-Mail:   ciaran.coyle@sita.aero<mailto:ciaran.coyle@sita.aero>
Direct:   +353 74 91 94740
Mobile: +353 86 8093378
CVS:   293 4740
Address:  SITA | Building One | Letterkenny Office Park | Letterkenny, Co. Donegal | Ireland


**Upcoming Leave :NONE*

Join the conversation:
[cid:image003.jpg@01D6F4E4.13A37A90]<http://www.sita.aero/resources/sita-social>
www.sita.aero<http://www.sita.aero/>
Please consider your environmental responsibility before printing

**Comment by phdhiren** [comment]
@cgcoyle, Thank you for confirming. Closing the issue.
