### ISSUE TITLE
Unable to re-purchase a rate plan that I have just canceled

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-m10n-drupal#265]
## Description

Unable to re-purchase a rate plan with this module that I have just canceled with end date: now. Although this is possible via API calls. (The Apigee Monetization API backend supports it.)

My gut says the root cause of the issue is [here](https://github.com/apigee/apigee-m10n-drupal/blob/72147d8d41ffe38b513e74847d9c9ffd2de844d6/src/Entity/PurchasedPlan.php#L272-L294) because this method does an incorrect calculation based on dates.

## Steps to Reproduce
1. Go to Prices & Plans and subscribe to a rate plan with start date: today
2. On your Purchased plans page, cancel the subscription with end date: now (or subscribe to an overlapping rate plan which has the same side effect)

## Actual Behavior
1. The cancalled rate plan is visible under "Active and Future Purchased Plans" on "Purchased plans"
2. You cannot subscribe to the rate plan again because the module does not allows it, it says "You have already purchased...".

## Expected Behavior
1. The cancalled rate plan is visible under "Cancelled and Expired Purchased Plans" on "Purchased plans"
2. You can subscribe to the rate plan again, immediatelly - since you have cancelled your subscription with end date: immediatelly.

## Version Info
1.8.0

**Comment by shishir-intelli** [comment]
@mxr576 thanks for reporting this issue.
PR https://github.com/apigee/apigee-m10n-drupal/pull/285

[Here](https://github.com/apigee/apigee-m10n-drupal/blob/72147d8d41ffe38b513e74847d9c9ffd2de844d6/src/Entity/PurchasedPlan.php#L274) it was only returning today's date and not proper datetime.
Example: _**Datetime Object  2021-05-14 00:00:00.000000"**_ 


In PR, implemented DateTimeImmutable and now getting "_**DateTimeImmutable Object ( [date] => 2021-05-14 07:25:29.652616 [timezone_type] => 3 [timezone] => UTC )**_" with proper datetime which resolves the further _If-else_ logic.

Note: In the existing code it allows user to be subscribed for the cancelled date and next day the subscription actually gets cancelled and user can re purchase the cancelled plan next day. 
In this PR the user can immediately cancel his subscription and also can re-purchase it again.

@cnovak [here](https://github.com/apigee/apigee-m10n-drupal/blob/72147d8d41ffe38b513e74847d9c9ffd2de844d6/src/Entity/Form/CancelPurchaseConfirmForm.php#L144) I am not sure why the cancelled "end date" is "start date" if user selects "NOW" for cancelling the subscription (4G), any reason for doing this?

**Comment by cnovak** [comment]
@giteshk @raakesh-blokhra I do not know the answer to @shishir-intelli's question in https://github.com/apigee/apigee-m10n-drupal/issues/265#issuecomment-841108808, do either of you have info?
