### ISSUE TITLE
Status report warns "Monetization is not enabled for your Apigee Edge organization." on Apigee X monetized trial org

### ISSUE THREAD

**Issue by giteshk** [apigee/apigee-m10n-drupal#280]
I have enabled Apigee Monetization module and connected to an Apigee X Trial org.
Using Apigee Monetization module Version: 8.x-1.10

![Screen Shot 2021-05-04 at 6 37 49 PM](https://user-images.githubusercontent.com/6208023/117078486-f7e09900-ad07-11eb-9255-2f31b6172595.png)

**Comment by raakesh-blokhra** [comment]
There's a new API call that needs some work to be done on this. Putting it in as a priority. Will keep you posted. 

Please note this error is only displayed for Apigee X connections, but does not impact any functionality and can be ignored as long as you can confirm that Monetization is enabled in the ORG. Will fix ASAP and confirm. Leaving this ticket open.
