### ISSUE TITLE
Move Apigee Monetization Add Credit  from Experimental to Apigee package

### ISSUE THREAD

**Issue by giteshk** [apigee/apigee-m10n-drupal#283]
Can we evaluate if Apigee Monetization Add Credit module is stable enough to be moved out of the Experimental package?

**Comment by mosornozebra** [comment]
can someone from Apigee let us know when this can be reviewed?

**Comment by phdhiren** [comment]
Hi @giteshk, we reviewed the module, there are a few issues that we need to resolve. Let's track it internally: b/188180386
