### ISSUE TITLE
Add Credit not working php7.4

### ISSUE THREAD

**Issue by asandil** [apigee/apigee-m10n-drupal#284]
## Description
I successfully enabled Add to Credit Module and can see Add Credit button on http://example.com/user/1/monetization/billing
If I click on Add Credit it makes Ajax request but nothing else happens.

## Steps to Reproduce
1. Enabled Add to credit module following https://www.drupal.org/docs/contributed-modules/apigee-monetization/enable-the-apigee-monetization-add-credit-module
2. Went to http://example.com/user/1/monetization/billing and clicked on Add Credit Button.
3. It makes Ajax request but doesnt move forward.

## Actual Behavior
it keeps making Ajax request as I see a loader below button.

## Expected Behavior
It should load a payment page to add credit.

## Screenshots
![image](https://user-images.githubusercontent.com/1023485/117861410-08b48000-b2af-11eb-892c-93d5e0d7d997.png)

## Version Info
1.10

**Comment by mosornozebra** [comment]
How often to Apigee devs look at this board and can we expect this bug to be reviewed and resolved soon?  This is impacting a Drupal 8 project so I would like to have some response I can report to the project team.  Regards

**Comment by phdhiren** [comment]
@asandil , 

Is there any additional custom module/theme is enabled when you've faced this error. Also, if you can send any php error log it will be helpful.

**Comment by asandil** [comment]
@phdhiren earlier I thought it could be due to some custom module or theme and installed new barebone kickstart apigee portal and I still find same error. Unfortunately It doesnt leave any log message.

**Comment by divya-intelli** [comment]
@asandil can you enable 'Apigee Edge Debug' module and check if any log is begin logged in '/admin/reports/dblog'.

**Comment by asandil** [comment]
PFA
![Web capture_12-5-2021_20148_dev2-developer zebra com](https://user-images.githubusercontent.com/1023485/117993018-fbee6580-b35c-11eb-868e-ef34ad9aa98e.jpeg)

**Comment by asandil** [comment]
@phdhiren could you get some time to look into this.
Let me know if you need more log details as I see bunch of other logs.

**Comment by mosornozebra** [comment]
@phdhiren please let us know if you will be able to look at this so we can set expectations on our end on it being resolved.  Thank you

**Comment by phdhiren** [comment]
@asandil 
Can you please run [Developer sync](https://www.drupal.org/docs/contributed-modules/apigee-edge/synchronize-developers-with-apigee-edge)? It seems the developer, which you're trying to add credit, doesn't exists in Apigee.

**Comment by asandil** [comment]
@phdhiren I tried with different account but it's same. See log
(REMOVED LOG)

**Comment by asandil** [comment]
I can do screen share based on your availability. Let me know good time for you.
Thank you

**Comment by phdhiren** [comment]
@asandil 

Can you share all debug logs with us? Here is the documentation on how to get the [debug log and remove credentials](https://www.drupal.org/docs/8/modules/apigee-edge/monitor-apigee-edge-debug-logs#configure). Mark @cnovak in the email as well.

**Comment by asandil** [comment]
@cnovak @phdhiren there are around 30 logs and I have attached here all logs.
Download link: (removed link)

**Comment by mosornozebra** [comment]
@cnovak @phdhiren Please let me know if we are able to do a screen share session and if we need to make this a higher priority because there is a project deadline associated for this with us.  Im not sure if there would be a cost associated with expediting.  Please let us know ASAP.  Thank you

**Comment by cnovak** [comment]
@phdhiren would the HAR file from Chrome developer tools help diagnose what the issue is when clicking the button? It would be good to know what error /network call is happening on the browser when the button is clicked.

**Comment by phdhiren** [comment]
@asandil @mosornozebra ,
The HAR file from Chrome developer tool will help diagnose, thanks @cnovak . Going forward please share any sensitive data on shared drive via email. Email ids are on @phdhiren and @cnovak profile page.

Additionally can you also try /admin/config/apigee-monetization/prepaid-balance/add-credit and disable 'Use Modal'?
Also if you can check with non-administrative user.

**Comment by mosornozebra** [comment]
Can we do a screen share session to get real time feedback.  We appreciate the assistence you have given us so far but we feel things would go quicker if we could get on a zoom or teams call.  Please let us know today.  AB in on IST time.
Marc

**Comment by giteshk** [comment]
@mosornozebra , The issue has been identified and added to our backlog. This is something only administrators or users with 'add credit to any developer prepaid balance' permission would see.  

Can you validate the add credit works with a non-admin user and report your findings.

**Comment by phdhiren** [comment]
@asandil @mosornozebra 
Can you please confirm if the non-admin users it worked?
Additionally, If you can confirm if the patch in https://github.com/apigee/apigee-m10n-drupal/pull/289 works for you, while we add more test case to the same.

**Comment by mosornozebra** [comment]
Thanks for following up with us.  The team is trying to resolve an sso/ssl issue right now with drupal 8 for the portal.  Once they resolve that they will implement your suggestion.  While on the subject are there are details you can share or have you experience any issues with Drupal8 on AWS SSO issues?

**Comment by asandil** [comment]
@phdhiren we removed administration role and given  Monetization Administrator
 Role to the user but when he tries to access https:/xxxxx.com/user/48082/monetization/billing receives an error saying
You are not authorized to access this page. What kind of role is required to access this page? 
Our Drupal 7 portal users with this role are able to add to add credit.

**Comment by phdhiren** [comment]
There are two permissions 'add credit to own developer prepaid balance' for registered user and  'add credit to any developer prepaid balance' for the admin. In a mean please also confirm if patch in #289 works for you or no.

**Comment by asandil** [comment]
@phdhiren I gave above mentioned permission and this is still throwing access denied error.

**Comment by phdhiren** [comment]
@asandil 
To access /user/[uid]/monetization/billing you'll need 'view own prepaid balance' or 'view any prepaid balance'

Above permission i.e. 'add credit to own developer prepaid balance' is for 'Add Credit'

**Comment by asandil** [comment]
Thank you @phdhiren this works if I remove Administrator Role. But Can you please confirm if this module is ready for production use as I still see this as an experimental module.  

 Can a team lead add credit for his developer? Please refer me to the documentation about setting up permission for all different roles?

**Comment by mosornozebra** [comment]
Yes good point AB is this sufficient to go live with.  Are there key things that the admin role can do that we wont have access to if issues arise?  We need to know before we say this is a viable option.

**Comment by phdhiren** [comment]
@asandil 
With the patch in #289, it should work along with team lead permission i.e. 'add credit to any developer prepaid balance' 
Yes, the module can be use for production, will merge above fix after review and then it will be available in next release. You can use with the patch given.

**Comment by asandil** [comment]
@phdhiren do you have any estimate on next release and moving this out of experimental module status?

**Comment by giteshk** [comment]
@asandil I will add it to the next milestone and update the release date shortly.

**Comment by mosornozebra** [comment]
Whats the date for official delivery?

**Comment by giteshk** [comment]
8.x-1.11 release date has been set to June 1st. 
We will also be moving the module out of Experimental.

**Comment by benhorgen** [comment]
That is great news. Thanks Gitesh.

**Comment by mosornozebra** [comment]
we are waiting for the business to test the patch provided so I would like to keep this open for now.

Marc

**Comment by mosornozebra** [comment]
Please info AB when the production patch is available for him to install on to our environment.

Marc

**Comment by raakesh-blokhra** [comment]
Just FYI, the changes have been published. You can run `composer update` to get the latest changes.
