### ISSUE TITLE
Drupal 8 Workflow with WorldsPay and Apigee

### ISSUE THREAD

**Issue by mosornozebra** [apigee/apigee-m10n-drupal#303]
We have migrated our site from Drupal 7 to Drupal 8 and the WorldPay payment is not working anymore. In our Drupal 7 site we were utilizing this architecture for payments which indicated that all the payments on worldpay was processed through Apigee. Please let us know how we can implement the same for Drupal 8 or if there is a contributed module out that we can download for implementation.

We need to understand how the systems are speaking to eachother.

**Comment by raakesh-blokhra** [comment]
@mosornozebra You can find information regarding payment gateway configuration here:
https://www.drupal.org/docs/8/modules/apigee-monetization/manage-payment-gateways

Hopefully that would answer your questions, if it doesn't please feel free to reopen this issue and let us know what can we help you with.

**Comment by mosornozebra** [comment]
Raakesh,  I beleive what my team is trying to understand is how the systems are speaking to eachother.  

1)and end user via drupal get taken to a worldpay screen to make their purchase.  
2)Worldpay send the payment information to APigee
3)apigee send the purchased product info to drupal

is this correct at a high level? We are just trying to understand the workflow.
