### ISSUE TITLE
Validate Edge runtime version for Apigee X

### ISSUE THREAD

**Issue by giteshk** [apigee/apigee-m10n-drupal#322]
Certain features of Monetization module may be dependent on the version of the Apigee X runtime.

This may become a problem for Hybrid customers who may be running an older version of Runtime.

Add an install requirement to this module to check minimum requirements of backend runtime.

**Comment by raakesh-blokhra** [comment]
@divya-intelli has this already been addressed or do we need to address it?

**Comment by giteshk** [comment]
No longer needed.
