### ISSUE TITLE
If you buy a rate plan as a developer, you cannot buy as a team

### ISSUE THREAD

**Issue by raakesh-blokhra** [apigee/apigee-m10n-drupal#337]
**Is your feature request related to a problem? Please describe.**
If you buy a rate plan as a developer, you cannot buy as a team (if the developer is the creator of the team), but you can buy a rate plan as team and the as a developer.

**Describe the solution you'd like**
The customer would like to have the same behavior in both cases.

**Comment by antoniocasella** [comment]
I think it is a bug, because if I purchase a rate plan as team admin then I'm able to purchase it in the personal area but the viceversa (purchasing the rate plan first in the personal area and then ad team admin) generate an error (telling that I already purchase the rate plan)
