### ISSUE TITLE
How to send email confirmation link to user who register on developer portal in on-prem model

### ISSUE THREAD

**Issue by RashidAli48** [apigee/apigee-m10n-drupal#340]
Is it possible to send an email confirmation link to the user email who registers on the developer portal? My requirement is that I want the user to confirm his/her email and activate his/her account rather than someone from management activate the account.
Right now developer registers on the developer portal and gets an email waiting for account approval. Someone from management with admin rights on the developer portal logged in and activate the developer account.

**Comment by phdhiren** [comment]
@RashidAli48 

It has more to do with Drupal then Apigee modules, consider reading following documentation on configuring it from admin panel.

https://www.drupal.org/docs/user_guide/en/config-user.html

**Comment by phdhiren** [comment]
@RashidAli48, Hope above documentation worked, closing the issue. Please feel free to reopen it, if requires.
