### ISSUE TITLE
Edge portal stop working Giving internal server error on every click

### ISSUE THREAD

**Issue by RashidAli48** [apigee/apigee-m10n-drupal#341]
Hi,
Our edge portal is not working. We are able to log in but when we try to open anything like proxies, products it gives internal server error. 
![image](https://user-images.githubusercontent.com/14312169/141741544-3119e0c2-d819-4f29-a3b9-94db578c2aba.png)

**Comment by phdhiren** [comment]
@RashidAli48 

You should connect to Apigee support on this.
The current issue queue is for open source Drupal module
