### ISSUE TITLE
Pricing & Plans page throw error

### ISSUE THREAD

**Issue by mjood47** [apigee/apigee-m10n-drupal#369]
hello,

i am getting this issue since i published one rate plan 

i cant log into the page 

a screen shot of the page 
![image](https://user-images.githubusercontent.com/33195698/158062783-d5652c1a-c009-4140-8458-26d58dfa4274.png)

and i am getting the below error in the logs 

Error: Call to a member function getEmail() on null in Drupal\apigee_m10n\Entity\Access\RatePlanSubscriptionAccessHandler->access() (line 102 of /var/www/devportal/web/modules/contrib/apigee_m10n/src/Entity/Access/RatePlanSubscriptionAccessHandler.php)
#0 /var/www/devportal/web/modules/contrib/apigee_m10n/src/Controller/PricingAndPlansController.php(171): Drupal\apigee_m10n\Entity\Access\RatePlanSubscriptionAccessHandler->access()
#1 [internal function]: Drupal\apigee_m10n\Controller\PricingAndPlansController->catalogPage()
#2 /var/www/devportal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
#3 /var/www/devportal/web/core/lib/Drupal/Core/Render/Renderer.php(564): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#4 /var/www/devportal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext()
#5 /var/www/devportal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
#6 /var/www/devportal/vendor/symfony/http-kernel/HttpKernel.php(158): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#7 /var/www/devportal/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#8 /var/www/devportal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle()
#9 /var/www/devportal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#10 /var/www/devportal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#11 /var/www/devportal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#12 /var/www/devportal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
#13 /var/www/devportal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#14 /var/www/devportal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#15 /var/www/devportal/web/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\StackedHttpKernel->handle()
#16 /var/www/devportal/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#17 {main}
.
Drupal 9.3.6

**Comment by phdhiren** [comment]
@mjood47 

Can you share output of `composer show` to understand the version used.

**Comment by MahmoudSayed96** [comment]
Hello 
I am facing the same issue also
Drupal version 9.5.10
name     : drupal/apigee_m10n
descrip. : Apigee Edge Monetization for Drupal
versions : * 2.1.0

**Comment by divya-intelli** [comment]
@MahmoudSayed96 , please share the output of `composer show`.

**Comment by MahmoudSayed96** [comment]
![image](https://github.com/apigee/apigee-m10n-drupal/assets/33764137/93c5b343-3a40-4cd7-85ff-2c0ea77759ca)

**Comment by divya-intelli** [comment]
@MahmoudSayed96 
Please help with below information to replicate the error.
1. PHP version
2. On which page are you getting this error along with the steps to follow.

**Comment by divya-intelli** [comment]
@mjood47 @MahmoudSayed96 , can you apply PR #442 and check if it resolves the issue.
