### ISSUE TITLE
Add datepicker format option to subscription start and end date or at least a format placeholder

### ISSUE THREAD

**Issue by cen1** [apigee/apigee-m10n-drupal#403]
## Description
The start and end date fields for subscription purchase are just plain text inputs. Customer has no clue what format the date should be inserted as. At the minimum, a placeholder of the date format should be added. An even better option would be to replace the text inputs with datepickers. This could be selectable with field format options.

<img width="428" alt="Screenshot 2022-10-21 at 13 42 25" src="https://user-images.githubusercontent.com/1158861/197188331-b4a6f387-0788-4231-8765-315fcc7887c0.png">

**Comment by divya-intelli** [comment]
Hi @cen1 ,

On the rate plan subscription page there is only a start date field. 
![Screenshot from 2022-10-25 14-18-45](https://user-images.githubusercontent.com/75604843/197733028-f1f00f4b-2253-4c1c-8244-0bb5fb671d62.png)

Can you let us know which page you are able to see start time and end time.

**Comment by cen1** [comment]
We see these two fields when we add the Purchase field to the rate plan display.

![Screenshot 2022-10-26 at 14 40 14](https://user-images.githubusercontent.com/1158861/198028804-7bce3f14-1479-424a-8e2a-17a7572e8a3f.png)

**Comment by divya-intelli** [comment]
Hi @cen1 ,
From the screenshot it seems like you're using ApigeeX.
For ApigeeX you need not add the start time and end time fields as these fields entry is not send in api request. The start time is set automatically by the api. Please disable these fields from 'admin/config/apigee-monetization/purchased-product-settings/form-display'.

**Comment by cen1** [comment]
Thank you. I would never in a million years figure out that is the form I needed to change.
