### ISSUE TITLE
Deprecation notice : The 'timestamp' formatter plugin 'tooltip' and 'time_diff' settings were added in drupal:10.1.0 and will be mandatory in Drupal 11.0.0.

### ISSUE THREAD

**Issue by divya-intelli** [apigee/apigee-m10n-drupal#461]
**Is your feature request related to a problem? Please describe.**
Deprecation notice : The 'timestamp' formatter plugin 'tooltip' and 'time_diff' settings were added in drupal:10.1.0 and will be mandatory in Drupal 11.0.0.
See https://www.drupal.org/node/2993639

**Comment by kedarkhaire** [comment]
Hi All,
As the changes made are compatible with D10 and not for D9 due to extended functionality of timestamp initiated in D10.
So when the support for D9 is closed, we will be ready to deploy this work, till now we will keep this work on hold.

Thanks!
