### ISSUE TITLE
WSOD after enabling the module

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-m10n-drupal#65]
It seems `commerceguys/intl` does not require bcmath extension in its composer.json because it is only required by [some classes that it contains](https://github.com/commerceguys/intl/search?q=bcmath&unscoped_q=bcmath). Although if this extension is not installed you get a WSOD after you enabled this module with this error in the logs:

```
  66   11/Mar 10:53   php      Error      RuntimeException: The bcmath extension is required by CurrencyFormatter. in CommerceGuys\Intl\Formatter\CurrencyFormatter->__construct() (line 81 of
 vendor/commerceguys/intl/src/Formatter/CurrencyFormatter.php).
```

Suggested solution:
As it seems this module depends on at least one class from `commerceguys/intl` that requires bcmath, add bcmath extension to this module's composer.json.

**Comment by Jaesin** [comment]
Good find, thank you. Can you provide steps to reproduce the issue?

**Comment by mxr576** [comment]
Install PHP without bcmath extension or disable it. Try to install the module on the UI.

**Comment by arunz6161** [comment]
Ran in to the same issue. To workaround, i installed php-bcmath and installed the module following  steps provided at https://www.drupal.org/project/apigee_m10n. I am assuming just doing either would have helped.

**Comment by mxr576** [comment]
Indeed, although as a user I should not be able to download (with Composer) or enable (in Drupal) this module if this extension is not available from the current host system.
