### ISSUE TITLE
Unable to install Add credit module

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-m10n-drupal#74]
Unable to install the Add credit module without manually installing Drupal Commerce components. Probably because this submodule does not have a composer.json therefore even if Composer Merge plugin is configured this submodule's dependencies does not get installed automatically with it. 
(As a best practice, I define dependencies in a submodule's composer.json as well, not just in the info.yml even I know that Drupal.org packagist tries to add the dependencies from the info.yml to the composer.json to ensure they get installed.)

![image](https://user-images.githubusercontent.com/1755573/54686178-fbf5d080-4b18-11e9-9e9e-a3342f114acd.png)

```sh
$ composer show | grep apigee_m10n
drupal/apigee_m10n                       1.0.0-alpha2       Apigee Edge Monetization for Drupal
```

**Comment by Jaesin** [comment]
This is by design `apigee_m10n_add_credit` module is optional so it's dependencies are not added to the drupal installation just because the `apigee_m10n` module is required in a project.

We can add a `composer.json` file to the submodule but in my opinion we wouldn't want to merge it.

**Comment by mxr576** [comment]
From one part, I do see the approach in the current implementation. Although, it is going to be confusing for simple end users to figure out what do they have to do to resolve this missing dependency issue.

For experienced ones, it is also a pain that they have to install the  `drupal/commerce` package manually on their site and they have to remove it manually because it becomes a dependency in the site's and not a dependency which is only installed because it is a dependency of an installed package.
Describing a submodule's composer.json only means that may get _installed_ (not enabled!) if Composer Merge plugin is configured on a project. In this setup, if drupal/commerce is not installed together with the MINT module then the discovery of the dependency conflicts between already installed components and the Add credit submodule gets postponed which can cause serious headaches for someone later.
When the Merge plugin is not installed it makes clear for developers that which versions should be installed from a dependency to make things work.

Just think about it, if it would not be `drupal/commerce` just a simple PHP library, you would do the same because you must define it as a dependency in the submodule's composer.json.

**Comment by cnovak** [comment]
It looks like we are missing documentation on the Add Credit module.  Looking at the [monetization module docs on Drupal.org](https://www.drupal.org/docs/8/modules/apigee-monetization) some change in organization of the docs is needed:

- [x] Add a section describing "Apigee Monetization Add Credit" module, that describes the overview, install, and configuration of this submodule.
- [x] The section [Support adding credit to a prepaid balance] should be part of the "Add Credit" module documentation
- [x] The section [Configure notifications for adding credit] should be part of the "Add Credit" module documentation
- [x] The [Install the Apigee Monetization Module](https://www.drupal.org/docs/8/modules/apigee-monetization/install-the-apigee-monetization-module) and the [project install info on the project home page](https://www.drupal.org/project/apigee_m10n) should have a section explaining that if you want to use the add credit functionality that you need to read the new "Apigee Monetization Add Credit" module documentation.
- [x] The installation instructions for add credit submodule should explain that you need to run `composer require drupal/commerce` to install dependencies of the add credit module.

**Comment by jbennett13** [comment]
Published here:  https://www.drupal.org/docs/8/modules/apigee-monetization/enable-the-apigee-monetization-add-credit-module

**Comment by jbennett13** [comment]
Added note in these two spots as well:  
https://www.drupal.org/project/apigee_m10n
https://www.drupal.org/docs/8/modules/apigee-monetization/install-the-apigee-monetization-module
