### ISSUE TITLE
Do allow to purchase plan rate plans that the current user already has an active subscription

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-m10n-drupal#78]
As a user with an active subscription for X rate plan I should not be able to purchase X rate plan again on the "Pricing & plans" page again.

Because if I try to purchase it I will get an error like this, no matter what start date I provide.

![image](https://user-images.githubusercontent.com/1755573/55063094-87221980-5077-11e9-87f6-6ef9338e721c.png)

**Comment by mxr576** [comment]
It seems this recently merged PR to dev addresses this problem.
https://github.com/apigee/apigee-m10n-drupal/commit/66ad5c5037fbc62fc56146c54ee01e713f2cf437

**Comment by Jaesin** [comment]
This was fixed in https://github.com/apigee/apigee-m10n-drupal/commit/66ad5c5037fbc62fc56146c54ee01e713f2cf437. There will be a followup because the subscribe page doesn't also contain the check.
