### ISSUE TITLE
"pricing and plans" page throws error

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-m10n-drupal#79]
Steps to reproduce: 
1. Follow https://docs.apigee.com/api-platform/publish/drupal/open-source-drupal-8#d8-install and install apigee_edge and apigee_monetization modules. 

2. Once done, click on the "pricing and plans" page

Error from watchdog logs:

`Error: Call to undefined method Drupal\apigee_edge\Entity\ApiProduct::isDefaultRevision() in Drupal\Core\Entity\EntityViewBuilder->getBuildDefaults() (line 181 of /app/web/core/lib/Drupal/Core/Entity/EntityViewBuilder.php) #0 /app/web/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(138): Drupal\Core\Entity\EntityViewBuilder->getBuildDefaults(Object(Drupal\apigee_edge\Entity\ApiProduct), 'default') #1 /app/web/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(111): Drupal\Core\Entity\EntityViewBuilder->viewMultiple(Array, 'default', 'und') #2 /app/web/core/lib/Drupal/Core/Field/Plugin/Field/FieldFormatter/EntityReferenceEntityFormatter.php(196): Drupal\Core\Entity\EntityViewBuilder->view(Object(Drupal\apigee_edge\Entity\ApiProduct), 'default', 'und') #3 /app/web/core/lib/Drupal/Core/Field/FormatterBase.php(80): Drupal\Core\Field\Plugin\Field\FieldFormatter\EntityReferenceEntityFormatter->viewElements(Object(Drupal\Core\Field\EntityReferenceFieldItemList), 'en') #4 /app/web/core/lib/Drupal/Core/Field/Plugin/Field/FieldFormatter/EntityReferenceFormatterBase.php(76): Drupal\Core\Field\FormatterBase->view(Object(Drupal\Core\Field\EntityReferenceFieldItemList), 'en') #5 /app/web/core/lib/Drupal/Core/Entity/Entity/EntityViewDisplay.php(263): Drupal\Core\Field\Plugin\Field\FieldFormatter\EntityReferenceFormatterBase->view(Object(Drupal\Core\Field\EntityReferenceFieldItemList), NULL) #6 /app/web/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(321): Drupal\Core\Entity\Entity\EntityViewDisplay->buildMultiple(Array) #7 /app/web/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(263): Drupal\Core\Entity\EntityViewBuilder->buildComponents(Array, Array, Array, 'default') #8 [internal function]: Drupal\Core\Entity\EntityViewBuilder->buildMultiple(Array) #9 /app/web/core/lib/Drupal/Core/Render/Renderer.php(378): call_user_func(Array, Array) #10 /app/web/core/lib/Drupal/Core/Render/Renderer.php(450): Drupal\Core\Render\Renderer->doRender(Array) #11 /app/web/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false) #12 /app/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(226): Drupal\Core\Render\Renderer->render(Array, false) #13 /app/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() #14 /app/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(227): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #15 /app/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(117): Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch)) #16 /app/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch)) #17 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #18 /app/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #19 /app/vendor/symfony/http-kernel/HttpKernel.php(156): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent)) #20 /app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #21 /app/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /app/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #25 /app/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #26 /app/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #27 /app/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #28 /app/web/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #29 /app/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #30 {main}.`

**Comment by minnur** [comment]
@arunz6161 thanks for reporting this issue. There is known issue in Drupal 8 core that causing the error (https://www.drupal.org/node/2951487). We did add the patch to the module however it appears that `composer require drupal/apigee_m10n` does not apply Drupal core patches specified in the composer.json of the `apigee_m10n` module. We are working on resolving this issue. Meanwhile I would suggest to add the following to the `extra` in your `composer.json`:
```
        "patches": {
            "drupal/core": {
                "`EntityViewBuilder::getBuildDefaults()` doesn't check for `RevisionableInterface`.": "https://www.drupal.org/files/issues/2019-01-10/2951487_15_no-tests.patch"
            }
        }
```

and run `composer update --lock` this should apply the patch.

**Comment by arunz6161** [comment]
Confirmed that this is no longer a issue with drupal/apigee_m10n 1.0.0-beta3
